### ISSUE TITLE
question - is it possible to use this without Cake?

### ISSUE THREAD

**Issue by pablocar80** [vhatsura/Cake.Systemctl#20]
Hello! I'm interested in using this library in a .NET Core application, to execute systemctl commands. Is it possible to use this library without Cake? Thank you!!

**Comment by vhatsura** [comment]
Hey, @pablocar80!

**Comment by pablocar80** [comment]
Hello @vhatsura, of course. I’m developing Integrative Studio (https://integrative.io). This is an IDE and programming language for web development, with its own web server, all fully integrated. Right now this works in Windows only and I’m migrating to Linux and MacOS. The web server runs as a service, and there is a small app to manage this service, including starting and stopping it. In Windows this is very easy to do in C# because the libraries for windows services are included. The equivalent in Linux is systemctl, however I could not find any library that does this. I thought of parsing the output of systemctl however that doesn’t sound like a very reliable approach, with all the different editions of Linux and variability.

**Comment by vhatsura** [comment]
Hey, @pablocar80. I got it your use case.
Does web server start every time when you open IDE? Or web server registers at once during IDE install and works all the time.

**Comment by pablocar80** [comment]
@vhatsura the 2nd option, registers once during install and works all the time (i.e. starts automatically on reboots)

**Comment by vhatsura** [comment]
@pablocar80, and the last questions. What do you use as installation tool? Do you investigate usage of cake as installation tool?

**Comment by pablocar80** [comment]
@vhatsura in the Windows version, what I have is an installer that is created with WIX installer. So it's a typical windows installer that lets you select whether you want to install the production server, and then installs and registers the windows service. This seems to be a pretty standard thing to do in Windows so all the tools available to create windows installers have some option to install services.

I have no experience in Cake, is this something that I could use as the equivalent of creating windows installers? That means, to distribute to people that do not know the ins and outs of what they're installing and simply press enter and/or click next?

**Comment by vhatsura** [comment]
@pablocar80, I got it. I'm afraid in such case cake is not accessible in your case. Also, I don't have any plans to distributed this addin without referencing to cake. Sorry for wasting your time. I believe you will find appropriate solution for your case

**Comment by pablocar80** [comment]
@vhatsura no wasted time at all, thank you a lot for your help and guidance.

**Comment by vhatsura** [comment]
@pablocar80, what do you mind if I close the issue?

**Comment by pablocar80** [comment]
Closing
